export const FAIL_TOAST = "Não deu. Tenta de novo.";
export const TOAST = {
  up: "Subiu",
  down: "Desceu",
  leftQueue: "Saiu da fila",
  lotClosed: "Lote fechado",
  confirmed: "Festa confirmada",
  rejected: "Candidato rejeitado",
  linked: "Mensagem vinculada",
  linkedMany: "Mensagens vinculadas",
  partyCreated: "Festa criada",
  dismissed: "Dispensado",
  restored: "Devolvido para a fila",
  unlinked: "Desvinculado",
  saved: "Salvo",
  listening: "Ouvindo",
  paused: "Pausado",
  enrolled: "Entrou na fila",
  lotOpened: "Lote aberto",
  classified: "Classificada",
  merged: "Festas fundidas",
  discarded: "Festa descartada",
  senderMuted: "Remetente silenciado",
  senderUnmuted: "Remetente reativado",
} as const;
